import os
import resend
from flask import current_app
from app.utils.logger import log_event
from app.utils.exceptions import ReplyIQError

class EmailDeliveryError(ReplyIQError):
    def __init__(self, message="Email delivery failed"):
        super().__init__(message, status_code=500, error_code="EMAIL_DELIVERY_FAILED")

def send_ai_reply_alert(to_email: str, reply_text: str, business_name: str, review_text: str) -> dict:
    """
    Track B: Despatch Loop. 
    Constructs an HTML email containing the generated reply and sends it 
    back to the user via Resend.
    """
    resend.api_key = current_app.config.get("RESEND_API_KEY", "")
    
    if not resend.api_key:
        log_event("email_service_skipped", reason="missing_api_key")
        return {"status": "skipped"}
        
    # The V4 Midnight Mesh Aesthetic translated to an inline HTML Email
    html_body = f"""
    <div style="font-family: 'Outfit', sans-serif; max-width: 600px; margin: 0 auto; background-color: #030712; color: #f8fafc; border-radius: 16px; overflow: hidden; border: 1px solid #1f2937;">
        
        <div style="background: linear-gradient(135deg, #4f46e5, #8b5cf6); padding: 32px 24px; text-align: center;">
            <p style="margin: 0; font-size: 24px; font-weight: 700;">💬 ReplyIQ</p>
            <p style="margin: 8px 0 0 0; color: rgba(255,255,255,0.8); font-size: 14px;">Your AI response is ready.</p>
        </div>

        <div style="padding: 32px 24px;">
            <p style="color: #9ca3af; font-size: 13px; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 8px;">From Customer</p>
            <div style="background: rgba(255,255,255,0.03); border-left: 3px solid #374151; padding: 16px; border-radius: 0 8px 8px 0; margin-bottom: 24px;">
                <p style="margin: 0; font-size: 14px; font-style: italic; color: #d1d5db;">"{review_text}"</p>
            </div>

            <p style="color: #8b5cf6; font-size: 13px; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 8px; font-weight: 600;">AI Recommended Reply</p>
            <div style="background: #111827; border: 1px solid #1f2937; padding: 20px; border-radius: 8px; margin-bottom: 24px;">
                <p style="margin: 0; font-size: 16px; line-height: 1.5; color: #f8fafc;">{reply_text}</p>
            </div>

            <div style="text-align: center;">
                <a href="https://replyiq.com" style="display: inline-block; background: #f8fafc; color: #030712; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 14px;">Log in to Paste</a>
            </div>
            
            <p style="margin-top: 32px; font-size: 12px; color: #6b7280; text-align: center;">
                Automatically generated by {business_name}'s 3-pass pipeline.
            </p>
        </div>
    </div>
    """
    
    try:
        response = resend.Emails.send({
            "from": "ReplyIQ <alerts@replyiq.com>", # This must match verified Resend domain
            "to": to_email,
            "subject": f"[{business_name}] AI Reply Generated",
            "html": html_body
        })
        log_event("email_sent", email_id=response.get("id", "unknown"), to=to_email)
        return {"id": response.get("id"), "status": "sent"}
    except Exception as e:
        log_event("email_delivery_failed", error=str(e), to=to_email)
        raise EmailDeliveryError(str(e))
